### ISSUE TITLE
Fix member.voice is NoneType when no network connectivity

### ISSUE THREAD

**Issue by CaptainDestructo** [LPD-VRChat/LPD-Officer-Monitor#64]
```
Error encountered in event: on_voice_state_update
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 210, in on_voice_state_update
    officer.go_on_duty()
  File "/home/ubuntu/LPD-Officer-Monitor/Classes/Officer.py", line 42, in go_on_duty
    f"{self.discord_name} is going on duty in {self.member.voice.channel.name}"
AttributeError: 'NoneType' object has no attribute 'channel'
```

This error occurs every time a user connects to an on-duty VC

**Comment by CaptainDestructo** [comment]
I finally was able to replicate this bug on the test server by disabling the network interface for a few minutes, then reconnecting. I have solved the problem in my PR. When on_ready is called, and if the Officer Manager or SQL Manager is already running, it restarts everything. I already verified that SQL Manager doesn't create additional connections when restarting.
